サインアップ実装
shinonome-inc/backend-final-assignment-Masaya pull request #2
Opened 2023-04-10 00:39 UTC by kinemasa

## 受講生の確認事項

- [✅ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ✅] Django Adminに，今まで作成したモデルを全て登録した
- [✅ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-10 14:03 UTC, HasegawaKota commented on accounts/views.py
> +class LoginView(LoginView):
```suggestion
class LoginView(auth_views.LoginView):
```
にしましょう

2023-04-10 14:03 UTC, HasegawaKota commented on accounts/views.py
> +from django.contrib.auth.views import LoginView, LogoutView
```suggestion
from django.contrib.auth import views as auth_views
```
としましょう

2023-04-10 14:03 UTC, HasegawaKota commented on accounts/tests.py
> +from accounts.forms import User
```suggestion
from .models import User
```
こちらの方がより丁寧です！！

2023-04-10 14:03 UTC, HasegawaKota commented on accounts/forms.py
> +        fields = ["username", "password"]
djangoが用意してくれるLoginViewではデフォルトでAuthenticationFormを使うことになっているのでここでの再定義は不要です。LoginFormを再定義したいなら何かカスタマイズしてください。プレースホルダーを用意するとか。
別にこのフォームは削除しちゃっても良いです。

2023-04-10 14:03 UTC, HasegawaKota commented on templates/accounts/login.htnl
> +
これはhtnlになっているので全消しでお願いします

2023-04-11 07:07 UTC, gaato requested changes
簡潔で良いと思います！数点コメントしました．

2023-04-11 07:07 UTC, gaato commented on accounts/forms.py
> +from accounts.models import User
`get_user_model` でも直接 `User` を import するでも全体で統一されていればどちらでも良いです！
今は直接 import で統一しているようなので編集は不要です．

2023-04-11 07:07 UTC, gaato commented on accounts/urls.py
> +    path("<slug:username>/", views.UserProfileView.as_view(), name="user_profile"),
```suggestion
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
```
[django.contrib.auth.models.User](https://docs.djangoproject.com/ja/4.1/ref/contrib/auth/#django.contrib.auth.models.User.username) の `username` は英数字の他に `_`, `@`, `+`, `.`, `-` が使えますが，[slug](https://docs.djangoproject.com/en/4.1/ref/validators/#validate-slug) ではそれらをカバーしきれないので普通に `str` で良いです．

2023-04-11 07:07 UTC, gaato commented on tweets/views.py
> +class HomeView(TemplateView, LoginRequiredMixin):
```suggestion
class HomeView(LoginRequiredMixin, TemplateView):
```
Mxin は View より左に書きましょう！左側に書いた基底クラスの方が優先されます．（メソッド解決順序という）

2023-04-11 09:14 UTC, gaato approved these changes

2023-04-11 09:14 UTC, gaato commented
LGTM!

2023-04-11 09:15 UTC, merged